#!/usr/bin/env python3
"""Generate common/video-cache.yaml -- an in-PSRAM clip cache.

Why generated: ESPHome has no arrays of components, so caching N frames means
N `online_image` entries. That is mechanical repetition, and mechanical
repetition should be produced by a program rather than maintained by hand.

    python tools/gen_video_cache.py [N]

The playback and loading logic is NOT repeated per frame -- it builds a
static array of the image pointers and drives them through OnlineImage's
public C++ API (set_url/update), so only the declarations are generated.
"""

from __future__ import annotations

import sys
from pathlib import Path

N = int(sys.argv[1]) if len(sys.argv) > 1 else 20
OUT = Path(__file__).resolve().parent.parent / "common" / "video-cache.yaml"

ids = [f"f{i:02d}" for i in range(N)]


def array_at(indent: int) -> str:
    """The pointer array, indented for its use site.

    Needed because these land inside YAML block scalars at two different
    depths, and a line indented less than the block's first line silently
    ends the block -- which surfaces as a YAML syntax error far below it.
    """
    pad = " " * indent
    return ("\n" + pad).join(f"id({i})," for i in ids).rstrip(",")

images = "\n".join(
    f"""  - id: {name}
    url: http://127.0.0.1/frame-cache-slot
    format: JPEG
    type: RGB565
    byte_order: BIG_ENDIAN
    resize: ${{display_width}}x${{display_height}}
    update_interval: never
    buffer_size: 32768
    on_download_finished:
      - lambda: |-
          id(clip_in_flight) = false;
          id(clip_loaded)++;
    on_error:
      - lambda: |-
          id(clip_in_flight) = false;
          id(clip_error) = true;
"""
    for name in ids
)

yaml = f"""# GENERATED by tools/gen_video_cache.py -- do not edit by hand.
# Regenerate with a different frame count:  python tools/gen_video_cache.py N
#
# Caches {N} pre-decoded frames in PSRAM and plays them back as pure blits.
#
# Why this is fast: the per-frame HTTP fetch is gone, and so is the JPEG
# decode. Both happen once, while loading. Playback is then one bulk
# draw_pixels_at() per frame straight out of PSRAM, which leaves only the
# panel transfer -- 240x240x2 bytes at 20 MHz = 46 ms, so ~21 fps is the
# hardware ceiling.
#
# Memory: {N} x ${{display_width}}*${{display_height}}*2 bytes. At 240x240 that is
# {N} x 115,200 = {N * 115200 / 1024 / 1024:.2f} MB of the 8 MB PSRAM. Raise N until that stops
# being comfortable; the XIAO also needs PSRAM for WiFi buffers and the heap.
#
# Requires common/content-pull.yaml (for content_url and the display).

globals:
  - id: clip_loading
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: clip_in_flight
    type: bool
    restore_value: false
    initial_value: 'false'

  # How many slots have been filled this load. Doubles as the next index to
  # request, so loading is just "fetch slot clip_loaded".
  - id: clip_loaded
    type: int
    restore_value: false
    initial_value: '0'

  - id: clip_frames
    type: int
    restore_value: false
    initial_value: '0'

  - id: clip_play_index
    type: int
    restore_value: false
    initial_value: '0'

  - id: clip_error
    type: bool
    restore_value: false
    initial_value: 'false'

  - id: clip_last_ms
    type: uint32_t
    restore_value: false
    initial_value: '0'

online_image:
{images}
script:
  # Fill the cache, one frame at a time. Sequential on purpose: the decoder is
  # single-threaded and parallel fetches would just queue behind each other
  # while multiplying peak memory.
  - id: clip_load
    then:
      - lambda: |-
          id(clip_loading) = true;
          id(clip_loaded) = 0;
          id(clip_in_flight) = false;
          id(clip_error) = false;
          id(clip_play_index) = 0;
          // Default to the full cache if the server has not said otherwise.
          if (id(clip_frames) <= 0 || id(clip_frames) > {N})
            id(clip_frames) = {N};

  # Blit the current cached frame. One bulk write; no decode, no network.
  - id: clip_show
    then:
      - lambda: |-
          static online_image::OnlineImage *slots[] = {{
              {array_at(14)}
          }};
          const int n = id(clip_loaded);
          if (n <= 0)
            return;
          auto *im = slots[id(clip_play_index) % n];
          if (!im->is_loaded())
            return;
          id(disp)->draw_pixels_at(0, 0, im->get_width(), im->get_height(),
                                   im->get_data_start(),
                                   display::COLOR_ORDER_RGB,
                                   display::COLOR_BITNESS_565, true, 0, 0, 0);

interval:
  # Loader: request the next empty slot whenever nothing is in flight.
  - interval: 50ms
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: |-
                  return id(clip_loading) && !id(clip_in_flight) &&
                         id(clip_loaded) < id(clip_frames) &&
                         id(content_url).state.find("/image?") != std::string::npos;
          then:
            - lambda: |-
                static online_image::OnlineImage *slots[] = {{
                    {array_at(20)}
                }};
                const int i = id(clip_loaded);
                std::string u = id(content_url).state;
                auto pos = u.find("/image?");
                u.replace(pos, 7, "/frame?");
                u += "&q=80&n=" + to_string(i);
                id(clip_in_flight) = true;
                slots[i]->set_url(u);
                slots[i]->update();
      - if:
          condition:
            lambda: 'return id(clip_loading) && id(clip_loaded) >= id(clip_frames);'
          then:
            - lambda: 'id(clip_loading) = false;'
            - logger.log: "Clip cached"

  # Playback straight out of PSRAM.
  - interval: 20ms
    then:
      - if:
          condition:
            and:
              - switch.is_on: clip_play
              - lambda: |-
                  if (id(clip_loading) || id(clip_loaded) <= 0)
                    return false;
                  const float t = id(target_fps).state;
                  const uint32_t target = t > 0 ? (uint32_t) t : 1;
                  return millis() - id(clip_last_ms) >= 1000u / target;
          then:
            - lambda: |-
                id(clip_last_ms) = millis();
                id(clip_play_index)++;
                id(frames_done)++;
            - script.execute: clip_show

number:
  # Set by the SERVER, which is the only side that knows whether the current
  # content is a clip: it reports the frame count (1 for a still). Everything
  # below is automatic from this one value -- >1 caches and plays, <=1 falls
  # back to the still path.
  - platform: template
    name: Clip Frames
    id: clip_server_frames
    optimistic: true
    restore_value: true
    initial_value: "0"
    min_value: 0
    max_value: {N}
    step: 1
    mode: box
    entity_category: config
    on_value:
      - if:
          condition:
            lambda: 'return x > 1;'
          then:
            # A clip. Cache it (re-cache if the count changed, which it does
            # whenever new content is pushed) and play it.
            - lambda: 'id(clip_frames) = (int) x < {N} ? (int) x : {N};'
            - script.execute: clip_load
          else:
            # A still. Stop playing and let content-pull draw it normally.
            - lambda: |-
                id(clip_loading) = false;
                id(clip_loaded) = 0;
                id(video_active) = false;

switch:
  # An override, not a prerequisite: on by default, so a clip plays without
  # anyone pressing anything. Turn it off to freeze on the current frame.
  - platform: template
    name: Play Cached Clip
    id: clip_play
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - lambda: 'id(video_active) = true;'
      - if:
          condition:
            lambda: |-
              return id(clip_loaded) == 0 && !id(clip_loading) &&
                     id(clip_server_frames).state > 1;
          then:
            - script.execute: clip_load
    turn_off_action:
      - lambda: 'id(video_active) = false;'

button:
  - platform: template
    name: Cache Clip
    id: cache_clip
    on_press:
      - script.execute: clip_load

sensor:
  - platform: template
    name: Clip Frames Cached
    id: clip_cached_sensor
    accuracy_decimals: 0
    update_interval: 2s
    lambda: 'return id(clip_loaded);'
"""

OUT.write_text(yaml, encoding="utf-8")
print(f"wrote {OUT} with {N} cached frames "
      f"({N * 115200 / 1024 / 1024:.2f} MB at 240x240)")
